[project]
name = "yt_dyablo"
version = "0.1.0"
description = "A yt plugin to read Dyablo datasets."
readme = "README.md"
authors = [
    { name = "Corentin Cadiou", email = "corentin.cadiou@iap.fr" }
]
requires-python = ">=3.10.4"
dependencies = [
    "h5py",
    "numpy>=1.21.2",
    "yt @ git+https://github.com/cphyc/yt.git@feature/support-non-cubic-zones",
    "unyt",
]

[project.optional-dependencies]
tests = [
    "pytest",
]

[project.entry-points."yt.frontends"]
DyabloDataset = "yt_dyablo.api:DyabloDataset"

[build-system]
requires = ["flit_core>=3.2,<4"]
build-backend = "flit_core.buildapi"

[tool.uv.workspace]
members = [
    "yt_dyablo",
]

[tool.ruff]
exclude = [
    "*/api.py",
    "*/__init__.py",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "C4",   # flake8-comprehensions
    "B",    # flake8-bugbear
    "G",    # flake8-logging-format
    "TCH",  # flake8-type-checking
    "YTT",  # flake8-2020
    "UP",   # pyupgrade
    "I",    # isort
    "NPY",  # numpy specific rules
    "RUF031"# incorrectly-parenthesized-tuple-in-subscript
]
ignore = [
    "E501",  # line too long
    "E741",  # Do not use variables named 'I', 'O', or 'l'
    "B018",  # Found useless expression.
]

[tool.ruff.lint.per-file-ignores]
"test_*" = ["NPY002"]


[tool.ruff.lint.isort]
combine-as-imports = true
known-third-party = [
  "numpy",
  "matplotlib",
  "unyt",
  "yaml",
  "pytest",
]
known-first-party = ["yt", "yt_dyablo"]
